name: Bug Report
description: "(⋟﹏⋞) I have encountered some problems"
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    id: check-answer
    attributes:
      label: CheckBox
      description: Please make sure
      options:
        - label: I have searched the issue list and found no similar issues.
          required: true
        - label: I use the official action instead of someone else's
          required: true
        - label: I have read the FAQ section in README.md
          required: true
        
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "Please type the configuration."
      value: |
        uses: dabao1955/kernel_build_action@main
        with:
          xxx: xxx
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        I used this action but have some error.
        Please help me!

    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add any relevant screenshots here, if any
      placeholder: |
        ![Screenshot_1](https://user-images.githubusercontent.com/25324935/128526303-9c644d80-8588-415e-b23b-fe905280352d.png)
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1.  

        2.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected it to work fine...
    validations:
      required: false

  - type: textarea
    id: errorlogs
    attributes:
      label: Error Logs
      description: Please add any relevant errlogs here, if any
      # render: log
      placeholder: |
        thread 'main' panicked at 'explicit panic', src/main.rs:2:5
        note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        Thanks for taking the time to fill out this bug! 
        If you need to discuss anything else, please go to github discussions.
    validations:
      required: false
