name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'
      - 'src/**/*.ts'
      - 'package.json'
      - 'yarn.lock'

  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'
      - 'src/**/*.ts'
      - 'package.json'
      - 'yarn.lock'

  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Kernel Source from Google Drive
        run: |
          wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=19uPZidD7pAqI0rHdGWehUKiMjVDvEUup' -O kernel_source.zip
          unzip kernel_source.zip -d kernel-source

      - name: Patch NetHunter
        run: |
          cd kernel-source
          git clone https://github.com/kimocoder/kali-nethunter-kernel-patches.git
          cd kali-nethunter-kernel-patches
          chmod +x patch.sh
          ./patch.sh ../

      - name: Build Kernel
        uses: ./
        with:
          kernel-url: https://github.com/mahinchasto-bot/samsung_a16_kernel
          kernel-dir: kernel-source
          kernel-branch: main
          config: a16_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 13
          disable-lto: true
          anykernel3: true
          
